import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import my.delphi.*; // Grammar classes generated by ANTLR 

import java.io.IOException;

public class Main {
    public static class DelphiPrinter extends delphiBaseVisitor<Object> {
        
        @Override
        public Object visitClassType(delphiParser.ClassTypeContext ctx) {
            System.out.println("  [Found a Class Definition]");
            return visitChildren(ctx);
        }

        @Override
        public Object visitObjectInstantiation(delphiParser.ObjectInstantiationContext ctx) {
            String className = ctx.identifier(0).getText();
            String methodName = ctx.identifier(1).getText();
            
            System.out.println("  [Found Object Creation]: Class=" + className + ", Method=" + methodName);
            return visitChildren(ctx);
        }
    }

    public static void main(String[] args) {
        if (args.length < 1) {
            System.err.println("Usage: java Main <file.pas>");
            return;
        }

        String fileName = args[0];

        try {
            CharStream input = CharStreams.fromFileName(fileName);
            delphiLexer lexer = new delphiLexer(input);
            CommonTokenStream tokens = new CommonTokenStream(lexer);

            delphiParser parser = new delphiParser(tokens);
            ParseTree tree = parser.program(); 

            DelphiPrinter visitor = new DelphiPrinter();
            visitor.visit(tree);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}